<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="A_BusinessPartner">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="A_BusinessPartnerType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="CreatedByUser">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="12"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="CreationDate" xmlns=""/>
                            <xs:element type="xs:time" nillable="true" minOccurs="0" maxOccurs="1" name="CreationTime" xmlns=""/>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="LastChangeDate" xmlns=""/>
                            <xs:element type="xs:time" nillable="true" minOccurs="0" maxOccurs="1" name="LastChangeTime" xmlns=""/>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="LastChangedByUser">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="12"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="BusinessPartnerIDByExtSystem">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="Customer">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
