<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- Root element -->
	<xs:element name="Record">
		<xs:complexType>
			<xs:sequence>
				<!-- TrsInv -->
				<xs:element name="TrsInv" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CMPNO" type="xs:string" minOccurs="0"/>
							<xs:element name="DBATCH" type="xs:string" minOccurs="0"/>
							<xs:element name="DSEQ" type="xs:string" minOccurs="0"/>
							<xs:element name="DDTTR" type="xs:string" minOccurs="0"/>
							<xs:element name="DTYPET" type="xs:string" minOccurs="0"/>
							<xs:element name="DDTPRD" type="xs:string" minOccurs="0"/>
							<xs:element name="TAB16" type="xs:string" minOccurs="0"/>
							<xs:element name="PMSLF" type="xs:string" minOccurs="0"/>
							<xs:element name="DUSIGE" type="xs:string" minOccurs="0"/>
							<xs:element name="DENTAF" type="xs:string" minOccurs="0"/>
							<xs:element name="DENTEX" type="xs:string" minOccurs="0"/>
							<xs:element name="DPROD" type="xs:string" minOccurs="0"/>
							<xs:element name="DTOTCA" type="xs:string" minOccurs="0"/>
							<xs:element name="DTOTCA1" type="xs:string" minOccurs="0"/>
							<xs:element name="DTPOID" type="xs:string" minOccurs="0"/>
							<xs:element name="DTPOID1" type="xs:string" minOccurs="0"/>
							<xs:element name="UTMES" type="xs:string" minOccurs="0"/>
							<xs:element name="DDTTRA" type="xs:string" minOccurs="0"/>
							<xs:element name="COUTPRD" type="xs:string" minOccurs="0"/>
							<xs:element name="FLGQ" type="xs:string" minOccurs="0"/>
							<xs:element name="FLGBLCK" type="xs:string" minOccurs="0"/>
							<xs:element name="FLGBLCKAF" type="xs:string" minOccurs="0"/>
							<xs:element name="FLGBLCKEX" type="xs:string" minOccurs="0"/>
							<xs:element name="LEG_BLOCK_STOCK_INDICATOR" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
